"""
Logic Audit Trail – EL'druin Bayesian Bridge
=============================================

Browse reasoning paths and probability trees generated by the Bayesian Bridge
intelligence audit system.

Features:
  - Submit raw news text for full Bayesian audit processing
  - Browse the audit log of past reasoning paths
  - Inspect probability trees and reasoning steps in detail
  - Visual confidence meters and probability tree explorer
"""

from __future__ import annotations

import os
import sys
from typing import Any, Dict

import streamlit as st

# Allow ``from utils.api_client import api_client`` when running from repo root.
_FRONTEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _FRONTEND_DIR not in sys.path:
    sys.path.insert(0, _FRONTEND_DIR)

from utils.api_client import APIClient  # noqa: E402
from components.audit_sidebar import render_audit_sidebar  # noqa: E402

# ---------------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="Logic Audit – EL-DRUIN",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Backend client
# ---------------------------------------------------------------------------
_backend_url_raw = os.environ.get("BACKEND_URL")
if not _backend_url_raw:
    raise RuntimeError(
        "BACKEND_URL environment variable is not set. "
        "Please configure it in your deployment environment. "
        "Expected format: https://your-backend-domain.com/api/v1"
    )
_backend_url = _backend_url_raw.rstrip("/")
_api = APIClient(base_url=_backend_url)

# ---------------------------------------------------------------------------
# Shared sidebar navigation
# ---------------------------------------------------------------------------
try:
    from components.sidebar import render_sidebar_navigation  # noqa: E402
    render_sidebar_navigation(is_subpage=True)
except Exception:
    pass

# ---------------------------------------------------------------------------
# Inject light theme CSS
# ---------------------------------------------------------------------------
_CSS_PATH = os.path.join(_FRONTEND_DIR, "assets", "custom_styles_light.css")
try:
    with open(_CSS_PATH, encoding="utf-8") as _css_f:
        st.markdown(f"<style>{_css_f.read()}</style>", unsafe_allow_html=True)
except FileNotFoundError:
    pass

# Ensure light background (override any dark theme)
st.markdown(
    "<style>.stApp { background-color: #F8FAFB !important; } "
    "h1,h2,h3,h4 { color: #0047AB !important; }</style>",
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------------
# Session state
# ---------------------------------------------------------------------------
if "audit_result" not in st.session_state:
    st.session_state.audit_result: Dict[str, Any] = {}
if "selected_path" not in st.session_state:
    st.session_state.selected_path: Dict[str, Any] = {}
if "selected_tree" not in st.session_state:
    st.session_state.selected_tree: Dict[str, Any] = {}

# ---------------------------------------------------------------------------
# Page header + onboarding
# ---------------------------------------------------------------------------
st.markdown(
    """
    <div style="margin-bottom:12px;">
        <h1 style="color:#0047AB;font-family:'Inter',sans-serif;font-weight:600;
                   letter-spacing:1px;font-size:1.6rem;margin-bottom:4px;">
            ⚖️ LOGIC AUDIT TRAIL
        </h1>
        <p style="color:#606060;font-size:0.85rem;font-style:italic;margin:0;">
            Bayesian Bridge — Every inference is mathematically tagged.
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)
st.info(
    "**What this page does:** The Logic Audit Trail runs news text through the "
    "Bayesian Bridge — a probabilistic reasoning system that tags every inference "
    "step with a confidence score and flags potential fallacies.\n\n"
    "**How to use:** Go to the **Submit Report** tab, paste article text, and click "
    "**Process Report**. Results appear in the **Audit Log** tab as a probability "
    "tree with reasoning steps. Use the right panel to inspect individual paths."
)

# ---------------------------------------------------------------------------
# Layout: [main content (7), detail sidebar (3)]
# ---------------------------------------------------------------------------
main_col, detail_col = st.columns([7, 3])

# ============================================================
# MAIN COLUMN
# ============================================================
with main_col:
    tab_submit, tab_log = st.tabs(["📝 Submit Report", "📋 Audit Log"])

    # ── Tab 1: Submit a new report for audit ─────────────────────────────
    with tab_submit:
        st.markdown(
            "<h4 style='color:#F0F0F0;font-weight:400;font-size:0.95rem;"
            "letter-spacing:1px;margin-bottom:12px;'>Submit News Report for Bayesian Audit</h4>",
            unsafe_allow_html=True,
        )

        news_text = st.text_area(
            "News article text",
            placeholder="Paste the raw news article text here…",
            height=180,
            key="audit_news_text",
            label_visibility="collapsed",
        )

        col_url, col_rel = st.columns([3, 1])
        with col_url:
            source_url = st.text_input(
                "Source URL",
                placeholder="https://reuters.com/...",
                key="audit_source_url",
            )
        with col_rel:
            source_reliability = st.slider(
                "Source reliability",
                min_value=0.0,
                max_value=1.0,
                value=0.8,
                step=0.05,
                key="audit_reliability",
            )

        source_type = st.selectbox(
            "Source type",
            options=["news_article", "user_input", "inference"],
            index=0,
            key="audit_source_type",
        )

        if st.button("⚖️ Analyse & Audit", type="primary", use_container_width=True):
            if not news_text.strip():
                st.warning("Please enter some news text before submitting.")
            else:
                with st.spinner("Running Bayesian audit pipeline…"):
                    result = _api.process_report_with_audit(
                        text=news_text.strip(),
                        source_url=source_url.strip(),
                        source_reliability=source_reliability,
                        source_type=source_type,
                    )
                if "error" in result:
                    st.error(f"Backend error: {result['error']}")
                else:
                    st.session_state.audit_result = result
                    # Fetch reasoning path and tree for sidebar
                    path_id = result.get("reasoning_path_id", "")
                    if path_id:
                        path_data = _api.get_reasoning_path(path_id)
                        if "error" not in path_data:
                            st.session_state.selected_path = path_data
                    tree = result.get("probability_tree", {})
                    if tree:
                        st.session_state.selected_tree = tree
                    st.success("✅ Bayesian audit complete!")

        # Results display
        result = st.session_state.audit_result
        if result and "reasoning_path_id" in result:
            st.markdown(
                "<hr style='border-color:#2D333B;margin:16px 0 12px 0'/>",
                unsafe_allow_html=True,
            )

            m1, m2, m3, m4 = st.columns(4)
            with m1:
                st.metric("Final Confidence", f"{result.get('final_confidence', 0):.2f}")
            with m2:
                st.metric("Branches", len(result.get("probability_tree", {}).get("interpretation_branches", [])))
            with m3:
                st.metric("Graph Changes", len(result.get("graph_changes", [])))
            with m4:
                status = result.get("audit_status", "pending_review")
                st.metric("Audit Status", status.replace("_", " ").title())

            st.markdown(
                f"<span style='color:#8B8B8B;font-size:0.75rem'>Reasoning Path ID: "
                f"<code>{result.get('reasoning_path_id','')}</code></span>",
                unsafe_allow_html=True,
            )

            # Selected branch summary
            best = result.get("selected_branch", {})
            if best:
                st.markdown(
                    "<h5 style='color:#0047AB;font-size:0.85rem;margin-top:12px;'>Selected Interpretation</h5>",
                    unsafe_allow_html=True,
                )
                st.markdown(
                    f"<div style='background:rgba(0,71,171,0.04);padding:10px 14px;border-radius:4px;"
                    f"border-left:3px solid #0047AB;'>"
                    f"<span style='color:#333333;font-size:0.85rem'>"
                    f"{best.get('interpretation','—')}</span><br>"
                    f"<span style='color:#606060;font-size:0.75rem'>"
                    f"weight={best.get('weight',0):.3f} | confidence={best.get('confidence',0):.2f}"
                    f"</span></div>",
                    unsafe_allow_html=True,
                )

            # Graph changes table
            changes = result.get("graph_changes", [])
            if changes:
                st.markdown(
                    "<h5 style='color:#0047AB;font-size:0.85rem;margin-top:12px;'>Graph Changes</h5>",
                    unsafe_allow_html=True,
                )
                import pandas as pd
                df = pd.DataFrame([
                    {
                        "Type": ch.get("change_type", ""),
                        "From": ch.get("from", ""),
                        "Relation": ch.get("relationship_type", ""),
                        "To": ch.get("to", ""),
                    }
                    for ch in changes
                ])
                st.dataframe(df, use_container_width=True, hide_index=True)

    # ── Tab 2: Browse audit log ──────────────────────────────────────────
    with tab_log:
        st.markdown(
            "<h4 style='color:#0047AB;font-weight:600;font-size:0.95rem;"
            "letter-spacing:0.5px;margin-bottom:12px;'>Recent Reasoning Paths</h4>",
            unsafe_allow_html=True,
        )

        col_limit, col_refresh = st.columns([2, 1])
        with col_limit:
            log_limit = st.slider("Max entries", min_value=5, max_value=50, value=10, step=5)
        with col_refresh:
            st.markdown("<div style='margin-top:28px'/>", unsafe_allow_html=True)
            if st.button("🔄 Refresh", use_container_width=True):
                pass  # re-runs automatically

        log_data = _api.get_audit_log(limit=log_limit)
        paths = log_data.get("paths", [])

        if not paths:
            if "error" in log_data:
                st.error(f"Could not load audit log: {log_data['error']}")
            else:
                st.info("No reasoning paths recorded yet. Submit a report to get started.")
        else:
            for i, path in enumerate(reversed(paths)):
                source = path.get("source", {})
                final_conf = path.get("final_confidence", 0.0)
                status = path.get("audit_status", "pending_review")
                path_id = path.get("path_id", "")
                ts = path.get("timestamp", "")[:19].replace("T", " ")

                status_color = {
                    "approved": "#22c55e",
                    "flagged": "#ef4444",
                    "pending_review": "#0047AB",
                }.get(status, "#6b7280")

                with st.expander(
                    f"[{ts}] {source.get('type','?')} — conf: {final_conf:.2f}",
                    expanded=False,
                ):
                    c1, c2, c3 = st.columns(3)
                    with c1:
                        st.markdown(
                            f"<span style='color:#A8A8A8;font-size:0.75rem'>Status</span><br>"
                            f"<span style='color:{status_color};font-size:0.85rem;font-weight:600'>"
                            f"{status.replace('_',' ').upper()}</span>",
                            unsafe_allow_html=True,
                        )
                    with c2:
                        st.markdown(
                            f"<span style='color:#A8A8A8;font-size:0.75rem'>Source reliability</span><br>"
                            f"<span style='color:#F0F0F0;font-size:0.85rem'>"
                            f"{source.get('reliability',0):.2f}</span>",
                            unsafe_allow_html=True,
                        )
                    with c3:
                        steps = len(path.get("inference_steps", []))
                        changes = len(path.get("graph_changes", []))
                        st.markdown(
                            f"<span style='color:#A8A8A8;font-size:0.75rem'>Steps / Changes</span><br>"
                            f"<span style='color:#F0F0F0;font-size:0.85rem'>{steps} / {changes}</span>",
                            unsafe_allow_html=True,
                        )

                    st.markdown(
                        f"<span style='color:#8B8B8B;font-size:0.72rem'>"
                        f"ID: <code>{path_id}</code></span>",
                        unsafe_allow_html=True,
                    )

                    if st.button(
                        "🔍 Inspect in sidebar",
                        key=f"inspect_{path_id}_{i}",
                        use_container_width=True,
                    ):
                        st.session_state.selected_path = path
                        # Try to load the probability tree for this path
                        tree_data = _api.get_probability_tree(path_id)
                        if "error" not in tree_data:
                            st.session_state.selected_tree = tree_data
                        else:
                            st.session_state.selected_tree = {}
                        st.rerun()

# ============================================================
# DETAIL COLUMN – Audit Sidebar
# ============================================================
with detail_col:
    render_audit_sidebar(
        reasoning_path=st.session_state.selected_path or None,
        probability_tree=st.session_state.selected_tree or None,
        container=detail_col,
    )
